name: validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: npx --yes markdownlint-cli2@0.23.0 "**/*.md"
